name: "Build"
on: [push, pull_request]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        platform:
           - { os: linux, arch: amd64 }
           - { os: linux, arch: arm64 }
           - { os: linux, arch: s390x }
           - { os: linux, arch: ppc64le }
           - { os: windows, arch: amd64 }
           - { os: darwin, arch: amd64 }

    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2.2.0
      with:
        go-version: "1.14"
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} make go-install
