name: "Build"
on: [push, pull_request]
jobs:
  linux-amd64:
    name: linux-amd64
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: "1.14"
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 make go-install

  linux-arm64:
    name: linux-arm64
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: "1.14"
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        GOOS=linux GOARCH=arm64 make go-install

  linux-s390x:
    name: linux-s390x
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: "1.14"
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        GOOS=linux GOARCH=s390x make go-install

  linux-ppc64le:
    name: linux-ppc64le
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: "1.14"
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        GOOS=linux GOARCH=ppc64le make go-install

  windows-amd64:
    name: windows-amd64
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: "1.14"
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 make go-install

  darwin-amd64:
    name: darwin-amd64
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: "1.14"
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        GOOS=darwin GOARCH=amd64 go install github.com/juju/juju/cmd/juju