name: "Client Tests"
on: [push, pull_request]
jobs:

  test-client-ubuntu:
    name: "Client Tests"
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        # macOS-latest is disabled because there is an issue of the tests timing
        # out. No effort has been done to work out why they currently timeout
        # on macOS, but we should investigate that to improve our coverage on
        # other clients.
        # To turn on macOS, just update the os to include it.
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ubuntu-latest]

    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.14
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: "Install Mongo Dependencies: ubuntu-latest"
      if: (matrix.os == 'ubuntu-latest')
      run: |
        # Remove the default mongo
        for version in "4.2" "4.4"; do
          sudo rm "/etc/apt/sources.list.d/mongodb-org-${version}.list" || true
        done
        sudo DEBIAN_FRONTEND=noninteractive apt-get purge -y mongodb-org
        sudo DEBIAN_FRONTEND=noninteractive apt autoremove
        sudo rm -rf /usr/bin/mongo* || true

        make install-mongo-dependencies

    - name: "Install Mongo Dependencies: macOS-latest"
      if: (matrix.os == 'macOS-latest')
      run: |
        curl -o mongodb-4.0.21.tgz https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.0.21.tgz
        tar xzvf mongodb-4.0.21.tgz
        sudo mkdir -p /usr/local/mongodb
        sudo mv mongodb-osx-x86_64-4.0.21/bin/* /usr/local/mongodb
        sudo mkdir -p /user/local/bin
        sudo ln -s /usr/local/mongodb/mongod /usr/local/bin/mongod
      shell: bash

    - name: "Remove Mongo Dependencies: windows-latest"
      if: (matrix.os == 'windows-latest')
      uses: crazy-max/ghaction-chocolatey@v1.4.2
      with:
        args: uninstall mongodb mongodb.install -y --all-versions

    - name: "Install Mongo Dependencies: windows-latest"
      if: (matrix.os == 'windows-latest')
      uses: crazy-max/ghaction-chocolatey@v1.4.2
      with:
        args: install mongodb.install --version=4.0.21 --allow-downgrade

    - name: Test client
      run: |
        # Jenkins can perform the full jujud testing.
        go test -v ./cmd/juju/... -check.v
        go test -v ./cmd/plugins/... -check.v
