name: "Update homebrew tap"
on:
  release:
    types: [published]
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  update-brew-tap:
    permissions:
      contents: none
    if: github.repository_owner == 'juju'
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@dd221ff435f42fa8102b5871bb1929af9d76476c # master
        with:
          token: "${{ secrets.TOKEN }}"
          formula: juju
          livecheck: true
