name: "Update homebrew tap"
on:
  release:
    types: [published]
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  update-brew-tap:
    permissions:
      contents: none
    if: github.repository_owner == 'juju'
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@02e79d9da43d79efa846d73695b6052cbbdbf48a # master
        with:
          token: "${{ secrets.TOKEN }}"
          formula: juju
          livecheck: true
